"""add student status fields

Revision ID: a6187dbdd1d8
Revises: 
Create Date: 2026-04-24 16:51:02.211567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6187dbdd1d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """添加学生状态字段
    
    - is_active: 是否在读，默认 True
    - enrollment_date: 入学日期，可空
    
    对于现有数据，所有学生的 is_active 将被设置为 True
    """
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 使用 batch_alter_table 以支持 SQLite 的 ALTER TABLE 限制
    with op.batch_alter_table('students', schema=None) as batch_op:
        # 添加 is_active 列，先允许为空，后续设置默认值后再改为非空
        batch_op.add_column(
            sa.Column(
                'is_active', 
                sa.Boolean(), 
                nullable=True,  # 先允许为空，以便处理现有数据
                comment='是否在读'
            )
        )
        # 添加 enrollment_date 列，可空
        batch_op.add_column(
            sa.Column(
                'enrollment_date', 
                sa.Date(), 
                nullable=True, 
                comment='入学日期'
            )
        )
    
    # 为现有数据设置默认值：is_active = True
    op.execute("UPDATE students SET is_active = 1 WHERE is_active IS NULL")
    
    # 现在将 is_active 列改为非空
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column(
            'is_active',
            existing_type=sa.Boolean(),
            nullable=False,
            server_default='1'  # 设置服务器默认值
        )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """移除学生状态字段"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('enrollment_date')
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###
