"""fix student user_id type and course status enum

Revision ID: b234c5e6f789
Revises: a6187dbdd1d8
Create Date: 2026-04-25 12:00:00.000000

修复ISSUE-001和ISSUE-002中的模型层修改：
- ISSUE-001: 将Student.user_id字段类型从INTEGER改为VARCHAR(36)
- ISSUE-002: 为Course.status字段添加枚举值约束（CHECK约束）

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b234c5e6f789'
down_revision: Union[str, None] = 'a6187dbdd1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库结构

    变更1 (ISSUE-001): 修改students表的user_id列类型
        - 从 INTEGER 类型改为 VARCHAR(36)
        - 用于存储UUID格式的用户ID

    变更2 (ISSUE-002): 为courses表的status列添加CHECK约束
        - 限制状态值为: 'active', 'inactive', 'draft'
        - 确保数据完整性
    """
    # ### commands auto generated by Alembic - please adjust! ###

    # ============================================================
    # 变更1: 修复 Student.user_id 字段类型从 int 改为 varchar(36)
    # 使用 batch_alter_table 以支持 SQLite 的 ALTER TABLE 限制
    # ============================================================
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column(
            'user_id',
            existing_type=sa.Integer(),
            type_=sa.String(36),
            existing_nullable=True,
            comment='关联的用户ID（UUID格式）'
        )

    # ============================================================
    # 变更2: 为 Course.status 添加枚举值约束（CHECK约束）
    # 注意：SQLAlchemy使用 Enum(native_enum=False) 时，
    #       在数据库层面会创建一个VARCHAR列加上CHECK约束
    # ============================================================
    op.create_check_constraint(
        'courses_status_check',
        'courses',
        "status IN ('active', 'inactive', 'draft')"
    )

    # 添加列注释说明（如果数据库支持）
    op.execute(
        "COMMENT ON COLUMN courses.status IS '课程状态: active-活跃, inactive-停用, draft-草稿'"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库结构到上一个版本

    回滚变更2: 移除 Course.status 的 CHECK 约束
    回滚变更1: 将 Student.user_id 改回整数类型
    """
    # ### commands auto generated by Alembic - please adjust! ###

    # ============================================================
    # 回滚变更2: 移除 Course.status 的约束
    # ============================================================
    op.drop_constraint('courses_status_check', 'courses', type_='check')

    # ============================================================
    # 回滚变更1: 将 Student.user_id 改回整数类型
    # 使用 batch_alter_table 以支持 SQLite 的 ALTER TABLE 限制
    # ============================================================
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column(
            'user_id',
            existing_type=sa.String(36),
            type_=sa.Integer(),
            existing_nullable=True,
            comment=None  # 移除注释
        )

    # ### end Alembic commands ###
