"""add ai conversation archive field

Revision ID: f890a1b2c345
Revises: a6187dbdd1d8
Create Date: 2026-07-11

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f890a1b2c345'
down_revision = 'e789f0a1b234'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_conversations', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_conversations', 'is_archived')
    # ### end Alembic commands ###
